//*******************************************************************************
//* Copyright (c) 2004-2014 Synchrotron SOLEIL
//* All rights reserved. This program and the accompanying materials
//* are made available under the terms of the GNU Lesser Public License v3
//* which accompanies this distribution, and is available at
//* http://www.gnu.org/licenses/lgpl.html
//******************************************************************************
static const char *RcsId = "$Header: /users/chaize/newsvn/cvsroot/Calculation/ImgBeamAnalyzer/src/ClassFactory.cpp,v 1.6 2010-04-07 13:14:50 ollupac Exp $";
//+=============================================================================
//
// file :        ClassFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible to create
//               all class singletin for a device server. It is called
//               at device server startup
//
// project :     TANGO Device Server
//
// $Author: ollupac $
//
// $Revision: 1.6 $
//
// $Log: not supported by cvs2svn $
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-=============================================================================
//
//      This file is generated by POGO
//  (Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#ifndef IBA_DLL_EXPORT

#include <IBASourceTango.h>
#include <ImgBeamAnalyzerClass.h>


/**
 *  Create ImgBeamAnalyzerClass singleton and store it in DServer object.
 */

void Tango::DServer::class_factory()
{
  add_class(ImgBeamAnalyzer_ns::ImgBeamAnalyzerClass::init("ImgBeamAnalyzer"));
}

#endif // ifndef IBA_DLL_EXPORT
