static const char *RcsId = "$Header: /users/chaize/newsvn/cvsroot/Calculation/ImgBeamAnalyzer/src/ClassFactory.cpp,v 1.4 2009-12-07 13:50:11 anoureddine Exp $";
//+=============================================================================
//
// file :        ClassFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible to create
//               all class singletin for a device server. It is called
//               at device server startup
//
// project :     TANGO Device Server
//
// $Author: anoureddine $
//
// $Revision: 1.4 $
//
// $Log: not supported by cvs2svn $
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#ifndef IBA_DLL_EXPORT

#include <ImgBeamAnalyzerClass.h>
#include <IBASourceTango.h>

/**
 *	Create ImgBeamAnalyzerClass singleton and store it in DServer object.
 */

void Tango::DServer::class_factory()
{
	add_class(ImgBeamAnalyzer_ns::ImgBeamAnalyzerClass::init("ImgBeamAnalyzer"));
}

#endif // ifndef IBA_DLL_EXPORT
